# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\'\n\x07get_req\x12\x0f\n\x07\x62\x61nk_id\x18\x01 \x01(\r\x12\x0b\n\x03\x64\x61y\x18\x02 \x01(\t\"[\n\tDataFrame\x12\x0c\n\x04name\x18\x01 \x01(\t\x12-\n\tdate_sent\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tbin_table\x18\x03 \x01(\x0c\x32\x38\n\x0fReturnPurchases\x12%\n\x0breturn_data\x12\x08.get_req\x1a\n.DataFrame0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GET_REQ._serialized_start=49
  _GET_REQ._serialized_end=88
  _DATAFRAME._serialized_start=90
  _DATAFRAME._serialized_end=181
  _RETURNPURCHASES._serialized_start=183
  _RETURNPURCHASES._serialized_end=239
# @@protoc_insertion_point(module_scope)
